version: "3.13"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
    - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-qu+jyxpz5xz_v18h7y-vc1sem=26m9a^ocu5q%af-l2%3b&#&&"
      - "DJANGO_DEBUG=False"
  db:
    image: postgres:15
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: