services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
    - db
    environment:
      - "DJANGO_SECRET_KEY=xExNq6ttvNqHKg844UVG2jqdNdC1c9276nE_xoEtVGVOmgn58sU"
      - "DJANGO_DEBUG=False"
      - "DJANGO_SECURE_SSL_REDIRECT=True"
  db:
    image: postgres:15
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: